### PR TITLE
Cards from Suppressive Fire and Fanatical Devotion Articles

### PR DESCRIPTION
**Pull request by ajmath**

### CODE REVIEW

**Comment by voidstate** [comment]
Hi 

Sorry I only just accepted this. The notification came while I was on holiday and went right out of my head.

:/

**Comment by voidstate** [comment]
I have added you as a collaborator. Does that mean you can pull without waiting for me?

**Comment by ajmath** [comment]
Yes.  I'll be able to merge my own PRs now.  Thank you very much!

**Comment by voidstate** [comment]
No problem. You seem to have a better grip on the dark arts of Git than me. And it's good to keep the repo as up to date as possible.

**Pull request merged**
